# Covid_ODE model configuration

data:
  age_mixing_matrix_term: data/polymod_normal_df.rds
  age_mixing_matrix_hol: data/polymod_no_school_df.rds
  mobility_matrix: data/movement.rds
  population_size: data/pop.rds
  reported_cases: data/DailyConfirmedCases_2020-03-20.csv

parameter:
  epsilon: 1.0e-6
  beta1: 0.04  # R0 2.4
  beta2: 0.33  # Contact with commuters 1/3rd of the time
  nu: 0.25
  gamma: 0.25

settings:
  start: 2020-02-19
  end: 2020-04-01
  holiday:
    - 2020-03-23
    - 2020-10-01
  bg_max_time: 2020-03-01
  time_step: 1.

output:
  simulation: covid_ode.hd5
