# Covid_ODE model configuration

data:
  mobility_matrix: data/mergedflows.csv
  population_size: data/c2019modagepop.csv
  commute_volume: data/201211_OFF_SEN_COVID19_road_traffic_national_table.xlsx
  reported_cases: data/LocalAuth_Time_Series_13122020.xlsx
  geopackage: data/UK2019mod_pop.gpkg

parameter:
  beta1: 0.291   # R0 2.4
  beta2: 0.876   # Contact with commuters 1/3rd of the time
  beta3: 1.0   # lockdown vs normal
  omega: 1.0   # Non-linearity parameter for commuting volume
  nu: 0.5      # E -> I transition rate
  gamma: 0.45  # I -> R transition rate
  xi:
    - 2.07
    - 0.15
    - -1.08
    - -0.78
    - -0.73
    - -0.51

settings:
  inference_period:
    - 2020-09-17
    - 2020-12-10
  time_step: 1.
  prediction_period:
    - 2020-02-19
    - 2020-08-01

mcmc:
  dmax: 84
  nmax: 50
  m: 1
  occult_nmax: 15
  num_event_time_updates: 35
  num_bursts: 200
  num_burst_samples: 50
  thin: 20
  prior:
    gamma:
      concentration: 2.0
      rate: 4.0

output:
  results_dir: output/testing
  posterior: posterior.hd5
  national_rt: national_rt.xlsx
  geopackage: prediction.gpkg
